baseURL = "https://kevindouglasdelong.net/"  # Matches your domain
languageCode = "en-us"
title = "Kevin Douglas Delong - Software Engineer Portfolio"
theme = "ananke"

[params]
  description = "Professional portfolio of Kevin Douglas Delong, specializing in backend and front-end development for web, mobile, and desktop applications."
  author = "Kevin Douglas Delong"
  favicon = "/images/favicon.ico"  # Add favicon to static/images/
  custom_css = ["/css/custom.css"]  # Optional: Add custom CSS file in static/css/

[[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 1
[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2
[[menu.main]]
  name = "Contact Me"
  url = "/contact/"
  weight = 3
[[menu.main]]
  name = "Resume"
  url = "/resume/"
  weight = 4
[[menu.main]]
  name = "Donate"
  url = "/donate/"
  weight = 5  # New donate page
